// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHP44loyXsmjJAb2XpCdurA_IjeNmcN_4',
    appId: '1:119081809507:web:f2005eadd1ac3c9193aa56',
    messagingSenderId: '119081809507',
    projectId: 'breakbite-demo',
    authDomain: 'breakbite-demo.firebaseapp.com',
    storageBucket: 'breakbite-demo.firebasestorage.app',
    measurementId: 'G-F5MGXLVTZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4vlqOduFKwyeUa6Cryu0F_jVrVPeKrbk',
    appId: '1:119081809507:android:a64e1f570a1987b093aa56',
    messagingSenderId: '119081809507',
    projectId: 'breakbite-demo',
    storageBucket: 'breakbite-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqYMEc1PtfkxjTYF9K_ko2BYpvtgCJ2Bg',
    appId: '1:119081809507:ios:9098959d146b4ea193aa56',
    messagingSenderId: '119081809507',
    projectId: 'breakbite-demo',
    storageBucket: 'breakbite-demo.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

}